#############################################################################
# Makefile for building: dudestar
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  dudestar.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile dudestar.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DVERSION_NUMBER="\"$(shell cd /home/fabian/git/dudestar;git rev-parse --short HEAD)\"" -DAMBEHW_SUPPORTED -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtMultimedia -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtSerialPort -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dudestar1.0.0
DISTDIR = /home/fabian/git/dudestar/.tmp/dudestar1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5Network -lQt5SerialPort -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CRCenc.cpp \
		DMRData.cpp \
		Golay24128.cpp \
		SHA256.cpp \
		YSFConvolution.cpp \
		YSFFICH.cpp \
		ambe.c \
		ambe3600x2400.c \
		ambe3600x2450.c \
		audioengine.cpp \
		cbptc19696.cpp \
		cgolay2087.cpp \
		chamming.cpp \
		codec.cpp \
		codec2/codebooks.cpp \
		codec2/codec2.cpp \
		codec2/kiss_fft.cpp \
		codec2/lpc.cpp \
		codec2/nlp.cpp \
		codec2/pack.cpp \
		codec2/qbase.cpp \
		codec2/quantise.cpp \
		crs129.cpp \
		dcscodec.cpp \
		dmrcodec.cpp \
		dudestar.cpp \
		ecc.c \
		httpmanager.cpp \
		iaxcodec.cpp \
		imbe7200x4400.c \
		imbe_vocoder/aux_sub.cc \
		imbe_vocoder/basicop2.cc \
		imbe_vocoder/ch_decode.cc \
		imbe_vocoder/ch_encode.cc \
		imbe_vocoder/dc_rmv.cc \
		imbe_vocoder/decode.cc \
		imbe_vocoder/dsp_sub.cc \
		imbe_vocoder/encode.cc \
		imbe_vocoder/imbe_vocoder.cc \
		imbe_vocoder/math_sub.cc \
		imbe_vocoder/pe_lpf.cc \
		imbe_vocoder/pitch_est.cc \
		imbe_vocoder/pitch_ref.cc \
		imbe_vocoder/qnt_sub.cc \
		imbe_vocoder/rand_gen.cc \
		imbe_vocoder/sa_decode.cc \
		imbe_vocoder/sa_encode.cc \
		imbe_vocoder/sa_enh.cc \
		imbe_vocoder/tbls.cc \
		imbe_vocoder/uv_synt.cc \
		imbe_vocoder/v_synt.cc \
		imbe_vocoder/v_uv_det.cc \
		levelmeter.cpp \
		m17codec.cpp \
		main.cpp \
		mbedec.cpp \
		mbeenc.cc \
		mbelib.c \
		nxdncodec.cpp \
		p25codec.cpp \
		refcodec.cpp \
		serialambe.cpp \
		serialmodem.cpp \
		xrfcodec.cpp \
		ysfcodec.cpp qrc_dudestar.cpp \
		moc_audioengine.cpp \
		moc_codec.cpp \
		moc_dcscodec.cpp \
		moc_dmrcodec.cpp \
		moc_dudestar.cpp \
		moc_httpmanager.cpp \
		moc_iaxcodec.cpp \
		moc_levelmeter.cpp \
		moc_m17codec.cpp \
		moc_nxdncodec.cpp \
		moc_p25codec.cpp \
		moc_refcodec.cpp \
		moc_serialambe.cpp \
		moc_serialmodem.cpp \
		moc_xrfcodec.cpp \
		moc_ysfcodec.cpp
OBJECTS       = CRCenc.o \
		DMRData.o \
		Golay24128.o \
		SHA256.o \
		YSFConvolution.o \
		YSFFICH.o \
		ambe.o \
		ambe3600x2400.o \
		ambe3600x2450.o \
		audioengine.o \
		cbptc19696.o \
		cgolay2087.o \
		chamming.o \
		codec.o \
		codebooks.o \
		codec2.o \
		kiss_fft.o \
		lpc.o \
		nlp.o \
		pack.o \
		qbase.o \
		quantise.o \
		crs129.o \
		dcscodec.o \
		dmrcodec.o \
		dudestar.o \
		ecc.o \
		httpmanager.o \
		iaxcodec.o \
		imbe7200x4400.o \
		aux_sub.o \
		basicop2.o \
		ch_decode.o \
		ch_encode.o \
		dc_rmv.o \
		decode.o \
		dsp_sub.o \
		encode.o \
		imbe_vocoder.o \
		math_sub.o \
		pe_lpf.o \
		pitch_est.o \
		pitch_ref.o \
		qnt_sub.o \
		rand_gen.o \
		sa_decode.o \
		sa_encode.o \
		sa_enh.o \
		tbls.o \
		uv_synt.o \
		v_synt.o \
		v_uv_det.o \
		levelmeter.o \
		m17codec.o \
		main.o \
		mbedec.o \
		mbeenc.o \
		mbelib.o \
		nxdncodec.o \
		p25codec.o \
		refcodec.o \
		serialambe.o \
		serialmodem.o \
		xrfcodec.o \
		ysfcodec.o \
		qrc_dudestar.o \
		moc_audioengine.o \
		moc_codec.o \
		moc_dcscodec.o \
		moc_dmrcodec.o \
		moc_dudestar.o \
		moc_httpmanager.o \
		moc_iaxcodec.o \
		moc_levelmeter.o \
		moc_m17codec.o \
		moc_nxdncodec.o \
		moc_p25codec.o \
		moc_refcodec.o \
		moc_serialambe.o \
		moc_serialmodem.o \
		moc_xrfcodec.o \
		moc_ysfcodec.o
DIST          = /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		dudestar.pro CRCenc.h \
		DMRData.h \
		DMRDefines.h \
		Golay24128.h \
		SHA256.h \
		YSFConvolution.h \
		YSFFICH.h \
		ambe.h \
		ambe3600x2400_const.h \
		ambe3600x2450_const.h \
		audioengine.h \
		cbptc19696.h \
		cgolay2087.h \
		chamming.h \
		codec.h \
		codec2/codec2.h \
		codec2/codec2_internal.h \
		codec2/defines.h \
		codec2/kiss_fft.h \
		codec2/lpc.h \
		codec2/nlp.h \
		codec2/qbase.h \
		codec2/quantise.h \
		crs129.h \
		dcscodec.h \
		dmrcodec.h \
		dudestar.h \
		ecc_const.h \
		httpmanager.h \
		iaxcodec.h \
		iaxdefines.h \
		imbe7200x4400_const.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/ch_decode.h \
		imbe_vocoder/ch_encode.h \
		imbe_vocoder/dc_rmv.h \
		imbe_vocoder/decode.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/globals.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/pe_lpf.h \
		imbe_vocoder/pitch_est.h \
		imbe_vocoder/pitch_ref.h \
		imbe_vocoder/qnt_sub.h \
		imbe_vocoder/rand_gen.h \
		imbe_vocoder/sa_decode.h \
		imbe_vocoder/sa_encode.h \
		imbe_vocoder/sa_enh.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/uv_synt.h \
		imbe_vocoder/v_synt.h \
		imbe_vocoder/v_uv_det.h \
		levelmeter.h \
		m17codec.h \
		mbedec.h \
		mbeenc.h \
		mbelib_const.h \
		mbelib_parms.h \
		nxdncodec.h \
		p25codec.h \
		refcodec.h \
		serialambe.h \
		serialmodem.h \
		vocoder_tables.h \
		xrfcodec.h \
		ysfcodec.h CRCenc.cpp \
		DMRData.cpp \
		Golay24128.cpp \
		SHA256.cpp \
		YSFConvolution.cpp \
		YSFFICH.cpp \
		ambe.c \
		ambe3600x2400.c \
		ambe3600x2450.c \
		audioengine.cpp \
		cbptc19696.cpp \
		cgolay2087.cpp \
		chamming.cpp \
		codec.cpp \
		codec2/codebooks.cpp \
		codec2/codec2.cpp \
		codec2/kiss_fft.cpp \
		codec2/lpc.cpp \
		codec2/nlp.cpp \
		codec2/pack.cpp \
		codec2/qbase.cpp \
		codec2/quantise.cpp \
		crs129.cpp \
		dcscodec.cpp \
		dmrcodec.cpp \
		dudestar.cpp \
		ecc.c \
		httpmanager.cpp \
		iaxcodec.cpp \
		imbe7200x4400.c \
		imbe_vocoder/aux_sub.cc \
		imbe_vocoder/basicop2.cc \
		imbe_vocoder/ch_decode.cc \
		imbe_vocoder/ch_encode.cc \
		imbe_vocoder/dc_rmv.cc \
		imbe_vocoder/decode.cc \
		imbe_vocoder/dsp_sub.cc \
		imbe_vocoder/encode.cc \
		imbe_vocoder/imbe_vocoder.cc \
		imbe_vocoder/math_sub.cc \
		imbe_vocoder/pe_lpf.cc \
		imbe_vocoder/pitch_est.cc \
		imbe_vocoder/pitch_ref.cc \
		imbe_vocoder/qnt_sub.cc \
		imbe_vocoder/rand_gen.cc \
		imbe_vocoder/sa_decode.cc \
		imbe_vocoder/sa_encode.cc \
		imbe_vocoder/sa_enh.cc \
		imbe_vocoder/tbls.cc \
		imbe_vocoder/uv_synt.cc \
		imbe_vocoder/v_synt.cc \
		imbe_vocoder/v_uv_det.cc \
		levelmeter.cpp \
		m17codec.cpp \
		main.cpp \
		mbedec.cpp \
		mbeenc.cc \
		mbelib.c \
		nxdncodec.cpp \
		p25codec.cpp \
		refcodec.cpp \
		serialambe.cpp \
		serialmodem.cpp \
		xrfcodec.cpp \
		ysfcodec.cpp
QMAKE_TARGET  = dudestar
DESTDIR       = 
TARGET        = dudestar


first: all
####### Build rules

$(TARGET): ui_dudestar.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dudestar.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		dudestar.pro \
		dudestar.qrc \
		/usr/lib/i386-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/i386-linux-gnu/libQt5Widgets.prl \
		/usr/lib/i386-linux-gnu/libQt5Gui.prl \
		/usr/lib/i386-linux-gnu/libQt5Network.prl \
		/usr/lib/i386-linux-gnu/libQt5SerialPort.prl \
		/usr/lib/i386-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile dudestar.pro
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
dudestar.pro:
dudestar.qrc:
/usr/lib/i386-linux-gnu/libQt5Multimedia.prl:
/usr/lib/i386-linux-gnu/libQt5Widgets.prl:
/usr/lib/i386-linux-gnu/libQt5Gui.prl:
/usr/lib/i386-linux-gnu/libQt5Network.prl:
/usr/lib/i386-linux-gnu/libQt5SerialPort.prl:
/usr/lib/i386-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile dudestar.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dudestar.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/i386-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CRCenc.h DMRData.h DMRDefines.h Golay24128.h SHA256.h YSFConvolution.h YSFFICH.h ambe.h ambe3600x2400_const.h ambe3600x2450_const.h audioengine.h cbptc19696.h cgolay2087.h chamming.h codec.h codec2/codec2.h codec2/codec2_internal.h codec2/defines.h codec2/kiss_fft.h codec2/lpc.h codec2/nlp.h codec2/qbase.h codec2/quantise.h crs129.h dcscodec.h dmrcodec.h dudestar.h ecc_const.h httpmanager.h iaxcodec.h iaxdefines.h imbe7200x4400_const.h imbe_vocoder/aux_sub.h imbe_vocoder/basic_op.h imbe_vocoder/ch_decode.h imbe_vocoder/ch_encode.h imbe_vocoder/dc_rmv.h imbe_vocoder/decode.h imbe_vocoder/dsp_sub.h imbe_vocoder/encode.h imbe_vocoder/globals.h imbe_vocoder/imbe.h imbe_vocoder/imbe_vocoder.h imbe_vocoder/math_sub.h imbe_vocoder/pe_lpf.h imbe_vocoder/pitch_est.h imbe_vocoder/pitch_ref.h imbe_vocoder/qnt_sub.h imbe_vocoder/rand_gen.h imbe_vocoder/sa_decode.h imbe_vocoder/sa_encode.h imbe_vocoder/sa_enh.h imbe_vocoder/tbls.h imbe_vocoder/typedef.h imbe_vocoder/typedefs.h imbe_vocoder/uv_synt.h imbe_vocoder/v_synt.h imbe_vocoder/v_uv_det.h levelmeter.h m17codec.h mbedec.h mbeenc.h mbelib_const.h mbelib_parms.h nxdncodec.h p25codec.h refcodec.h serialambe.h serialmodem.h vocoder_tables.h xrfcodec.h ysfcodec.h $(DISTDIR)/
	$(COPY_FILE) --parents CRCenc.cpp DMRData.cpp Golay24128.cpp SHA256.cpp YSFConvolution.cpp YSFFICH.cpp ambe.c ambe3600x2400.c ambe3600x2450.c audioengine.cpp cbptc19696.cpp cgolay2087.cpp chamming.cpp codec.cpp codec2/codebooks.cpp codec2/codec2.cpp codec2/kiss_fft.cpp codec2/lpc.cpp codec2/nlp.cpp codec2/pack.cpp codec2/qbase.cpp codec2/quantise.cpp crs129.cpp dcscodec.cpp dmrcodec.cpp dudestar.cpp ecc.c httpmanager.cpp iaxcodec.cpp imbe7200x4400.c imbe_vocoder/aux_sub.cc imbe_vocoder/basicop2.cc imbe_vocoder/ch_decode.cc imbe_vocoder/ch_encode.cc imbe_vocoder/dc_rmv.cc imbe_vocoder/decode.cc imbe_vocoder/dsp_sub.cc imbe_vocoder/encode.cc imbe_vocoder/imbe_vocoder.cc imbe_vocoder/math_sub.cc imbe_vocoder/pe_lpf.cc imbe_vocoder/pitch_est.cc imbe_vocoder/pitch_ref.cc imbe_vocoder/qnt_sub.cc imbe_vocoder/rand_gen.cc imbe_vocoder/sa_decode.cc imbe_vocoder/sa_encode.cc imbe_vocoder/sa_enh.cc imbe_vocoder/tbls.cc imbe_vocoder/uv_synt.cc imbe_vocoder/v_synt.cc imbe_vocoder/v_uv_det.cc levelmeter.cpp m17codec.cpp main.cpp mbedec.cpp mbeenc.cc mbelib.c nxdncodec.cpp p25codec.cpp refcodec.cpp serialambe.cpp serialmodem.cpp xrfcodec.cpp ysfcodec.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dudestar.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_dudestar.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_dudestar.cpp
qrc_dudestar.cpp: dudestar.qrc \
		/usr/lib/qt5/bin/rcc \
		images/dudestar.png
	/usr/lib/qt5/bin/rcc -name dudestar dudestar.qrc -o qrc_dudestar.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/i386-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/i386-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_audioengine.cpp moc_codec.cpp moc_dcscodec.cpp moc_dmrcodec.cpp moc_dudestar.cpp moc_httpmanager.cpp moc_iaxcodec.cpp moc_levelmeter.cpp moc_m17codec.cpp moc_nxdncodec.cpp moc_p25codec.cpp moc_refcodec.cpp moc_serialambe.cpp moc_serialmodem.cpp moc_xrfcodec.cpp moc_ysfcodec.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_audioengine.cpp moc_codec.cpp moc_dcscodec.cpp moc_dmrcodec.cpp moc_dudestar.cpp moc_httpmanager.cpp moc_iaxcodec.cpp moc_levelmeter.cpp moc_m17codec.cpp moc_nxdncodec.cpp moc_p25codec.cpp moc_refcodec.cpp moc_serialambe.cpp moc_serialmodem.cpp moc_xrfcodec.cpp moc_ysfcodec.cpp
moc_audioengine.cpp: audioengine.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include audioengine.h -o moc_audioengine.cpp

moc_codec.cpp: audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		codec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include codec.h -o moc_codec.cpp

moc_dcscodec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		dcscodec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include dcscodec.h -o moc_dcscodec.cpp

moc_dmrcodec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		DMRData.h \
		DMRDefines.h \
		cbptc19696.h \
		dmrcodec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include dmrcodec.h -o moc_dmrcodec.cpp

moc_dudestar.cpp: httpmanager.h \
		levelmeter.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		refcodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		dcscodec.h \
		xrfcodec.h \
		ysfcodec.h \
		YSFFICH.h \
		dmrcodec.h \
		DMRData.h \
		DMRDefines.h \
		cbptc19696.h \
		p25codec.h \
		nxdncodec.h \
		m17codec.h \
		codec2/codec2.h \
		codec2/codec2_internal.h \
		codec2/kiss_fft.h \
		codec2/defines.h \
		codec2/nlp.h \
		codec2/quantise.h \
		codec2/qbase.h \
		iaxcodec.h \
		dudestar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include dudestar.h -o moc_dudestar.cpp

moc_httpmanager.cpp: httpmanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include httpmanager.h -o moc_httpmanager.cpp

moc_iaxcodec.cpp: audioengine.h \
		iaxcodec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include iaxcodec.h -o moc_iaxcodec.cpp

moc_levelmeter.cpp: levelmeter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include levelmeter.h -o moc_levelmeter.cpp

moc_m17codec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		codec2/codec2.h \
		codec2/codec2_internal.h \
		codec2/kiss_fft.h \
		codec2/defines.h \
		codec2/nlp.h \
		codec2/quantise.h \
		codec2/qbase.h \
		m17codec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include m17codec.h -o moc_m17codec.cpp

moc_nxdncodec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		nxdncodec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include nxdncodec.h -o moc_nxdncodec.cpp

moc_p25codec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		p25codec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include p25codec.h -o moc_p25codec.cpp

moc_refcodec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		refcodec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include refcodec.h -o moc_refcodec.cpp

moc_serialambe.cpp: serialambe.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include serialambe.h -o moc_serialambe.cpp

moc_serialmodem.cpp: serialmodem.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include serialmodem.h -o moc_serialmodem.cpp

moc_xrfcodec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		xrfcodec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include xrfcodec.h -o moc_xrfcodec.cpp

moc_ysfcodec.cpp: codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		YSFFICH.h \
		ysfcodec.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/fabian/git/dudestar/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fabian/git/dudestar -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtSerialPort -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ysfcodec.h -o moc_ysfcodec.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dudestar.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dudestar.h
ui_dudestar.h: dudestar.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dudestar.ui -o ui_dudestar.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

CRCenc.o: CRCenc.cpp CRCenc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CRCenc.o CRCenc.cpp

DMRData.o: DMRData.cpp DMRData.h \
		DMRDefines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DMRData.o DMRData.cpp

Golay24128.o: Golay24128.cpp Golay24128.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Golay24128.o Golay24128.cpp

SHA256.o: SHA256.cpp SHA256.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SHA256.o SHA256.cpp

YSFConvolution.o: YSFConvolution.cpp YSFConvolution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YSFConvolution.o YSFConvolution.cpp

YSFFICH.o: YSFFICH.cpp YSFConvolution.h \
		YSFDefines.h \
		Golay24128.h \
		YSFFICH.h \
		CRCenc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YSFFICH.o YSFFICH.cpp

ambe.o: ambe.c ambe.h \
		mbelib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ambe.o ambe.c

ambe3600x2400.o: ambe3600x2400.c mbelib.h \
		ambe3600x2400_const.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ambe3600x2400.o ambe3600x2400.c

ambe3600x2450.o: ambe3600x2450.c mbelib.h \
		ambe3600x2450_const.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ambe3600x2450.o ambe3600x2450.c

audioengine.o: audioengine.cpp audioengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audioengine.o audioengine.cpp

cbptc19696.o: cbptc19696.cpp cbptc19696.h \
		chamming.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cbptc19696.o cbptc19696.cpp

cgolay2087.o: cgolay2087.cpp cgolay2087.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cgolay2087.o cgolay2087.cpp

chamming.o: chamming.cpp chamming.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chamming.o chamming.cpp

codec.o: codec.cpp codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codec.o codec.cpp

codebooks.o: codec2/codebooks.cpp codec2/defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codebooks.o codec2/codebooks.cpp

codec2.o: codec2/codec2.cpp codec2/nlp.h \
		codec2/defines.h \
		codec2/lpc.h \
		codec2/quantise.h \
		codec2/qbase.h \
		codec2/codec2.h \
		codec2/codec2_internal.h \
		codec2/kiss_fft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codec2.o codec2/codec2.cpp

kiss_fft.o: codec2/kiss_fft.cpp codec2/defines.h \
		codec2/kiss_fft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kiss_fft.o codec2/kiss_fft.cpp

lpc.o: codec2/lpc.cpp codec2/defines.h \
		codec2/lpc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lpc.o codec2/lpc.cpp

nlp.o: codec2/nlp.cpp codec2/defines.h \
		codec2/nlp.h \
		codec2/kiss_fft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nlp.o codec2/nlp.cpp

pack.o: codec2/pack.cpp codec2/defines.h \
		codec2/quantise.h \
		codec2/qbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pack.o codec2/pack.cpp

qbase.o: codec2/qbase.cpp codec2/qbase.h \
		codec2/defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbase.o codec2/qbase.cpp

quantise.o: codec2/quantise.cpp codec2/defines.h \
		codec2/quantise.h \
		codec2/qbase.h \
		codec2/lpc.h \
		codec2/kiss_fft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quantise.o codec2/quantise.cpp

crs129.o: crs129.cpp crs129.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crs129.o crs129.cpp

dcscodec.o: dcscodec.cpp dcscodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		CRCenc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcscodec.o dcscodec.cpp

dmrcodec.o: dmrcodec.cpp dmrcodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		DMRData.h \
		DMRDefines.h \
		cbptc19696.h \
		cgolay2087.h \
		crs129.h \
		SHA256.h \
		CRCenc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dmrcodec.o dmrcodec.cpp

dudestar.o: dudestar.cpp dudestar.h \
		httpmanager.h \
		levelmeter.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		refcodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		dcscodec.h \
		xrfcodec.h \
		ysfcodec.h \
		YSFFICH.h \
		dmrcodec.h \
		DMRData.h \
		DMRDefines.h \
		cbptc19696.h \
		p25codec.h \
		nxdncodec.h \
		m17codec.h \
		codec2/codec2.h \
		codec2/codec2_internal.h \
		codec2/kiss_fft.h \
		codec2/defines.h \
		codec2/nlp.h \
		codec2/quantise.h \
		codec2/qbase.h \
		iaxcodec.h \
		ui_dudestar.h \
		SHA256.h \
		crs129.h \
		cgolay2087.h \
		micpermission.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dudestar.o dudestar.cpp

ecc.o: ecc.c ecc_const.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ecc.o ecc.c

httpmanager.o: httpmanager.cpp httpmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpmanager.o httpmanager.cpp

iaxcodec.o: iaxcodec.cpp iaxcodec.h \
		audioengine.h \
		iaxdefines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iaxcodec.o iaxcodec.cpp

imbe7200x4400.o: imbe7200x4400.c mbelib.h \
		imbe7200x4400_const.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o imbe7200x4400.o imbe7200x4400.c

aux_sub.o: imbe_vocoder/aux_sub.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/tbls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aux_sub.o imbe_vocoder/aux_sub.cc

basicop2.o: imbe_vocoder/basicop2.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basicop2.o imbe_vocoder/basicop2.cc

ch_decode.o: imbe_vocoder/ch_decode.cc imbe_vocoder/globals.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/ch_decode.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/aux_sub.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ch_decode.o imbe_vocoder/ch_decode.cc

ch_encode.o: imbe_vocoder/ch_encode.cc imbe_vocoder/globals.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/ch_encode.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/aux_sub.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ch_encode.o imbe_vocoder/ch_encode.cc

dc_rmv.o: imbe_vocoder/dc_rmv.cc imbe_vocoder/globals.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/dc_rmv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dc_rmv.o imbe_vocoder/dc_rmv.cc

decode.o: imbe_vocoder/decode.cc imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/globals.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/ch_decode.h \
		imbe_vocoder/sa_decode.h \
		imbe_vocoder/sa_enh.h \
		imbe_vocoder/v_synt.h \
		imbe_vocoder/uv_synt.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o decode.o imbe_vocoder/decode.cc

dsp_sub.o: imbe_vocoder/dsp_sub.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dsp_sub.o imbe_vocoder/dsp_sub.cc

encode.o: imbe_vocoder/encode.cc imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/globals.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/dc_rmv.h \
		imbe_vocoder/pe_lpf.h \
		imbe_vocoder/pitch_est.h \
		imbe_vocoder/pitch_ref.h \
		imbe_vocoder/v_uv_det.h \
		imbe_vocoder/sa_encode.h \
		imbe_vocoder/ch_encode.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encode.o imbe_vocoder/encode.cc

imbe_vocoder.o: imbe_vocoder/imbe_vocoder.cc imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imbe_vocoder.o imbe_vocoder/imbe_vocoder.cc

math_sub.o: imbe_vocoder/math_sub.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/math_sub.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o math_sub.o imbe_vocoder/math_sub.cc

pe_lpf.o: imbe_vocoder/pe_lpf.cc imbe_vocoder/globals.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/pe_lpf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pe_lpf.o imbe_vocoder/pe_lpf.cc

pitch_est.o: imbe_vocoder/pitch_est.cc imbe_vocoder/globals.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/pitch_est.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pitch_est.o imbe_vocoder/pitch_est.cc

pitch_ref.o: imbe_vocoder/pitch_ref.cc imbe_vocoder/globals.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/pitch_ref.h \
		imbe_vocoder/imbe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pitch_ref.o imbe_vocoder/pitch_ref.cc

qnt_sub.o: imbe_vocoder/qnt_sub.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/qnt_sub.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qnt_sub.o imbe_vocoder/qnt_sub.cc

rand_gen.o: imbe_vocoder/rand_gen.cc imbe_vocoder/rand_gen.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/basic_op.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rand_gen.o imbe_vocoder/rand_gen.cc

sa_decode.o: imbe_vocoder/sa_decode.cc imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/globals.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/qnt_sub.h \
		imbe_vocoder/sa_decode.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sa_decode.o imbe_vocoder/sa_decode.cc

sa_encode.o: imbe_vocoder/sa_encode.cc imbe_vocoder/globals.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/qnt_sub.h \
		imbe_vocoder/sa_encode.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sa_encode.o imbe_vocoder/sa_encode.cc

sa_enh.o: imbe_vocoder/sa_enh.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/qnt_sub.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/sa_enh.h \
		imbe_vocoder/imbe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sa_enh.o imbe_vocoder/sa_enh.cc

tbls.o: imbe_vocoder/tbls.cc imbe_vocoder/tbls.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tbls.o imbe_vocoder/tbls.cc

uv_synt.o: imbe_vocoder/uv_synt.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/uv_synt.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/rand_gen.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uv_synt.o imbe_vocoder/uv_synt.cc

v_synt.o: imbe_vocoder/v_synt.cc imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/v_synt.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/rand_gen.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v_synt.o imbe_vocoder/v_synt.cc

v_uv_det.o: imbe_vocoder/v_uv_det.cc imbe_vocoder/globals.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/aux_sub.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/tbls.h \
		imbe_vocoder/v_uv_det.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v_uv_det.o imbe_vocoder/v_uv_det.cc

levelmeter.o: levelmeter.cpp levelmeter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o levelmeter.o levelmeter.cpp

m17codec.o: m17codec.cpp m17codec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		codec2/codec2.h \
		codec2/codec2_internal.h \
		codec2/kiss_fft.h \
		codec2/defines.h \
		codec2/nlp.h \
		codec2/quantise.h \
		codec2/qbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o m17codec.o m17codec.cpp

main.o: main.cpp dudestar.h \
		httpmanager.h \
		levelmeter.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		refcodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		dcscodec.h \
		xrfcodec.h \
		ysfcodec.h \
		YSFFICH.h \
		dmrcodec.h \
		DMRData.h \
		DMRDefines.h \
		cbptc19696.h \
		p25codec.h \
		nxdncodec.h \
		m17codec.h \
		codec2/codec2.h \
		codec2/codec2_internal.h \
		codec2/kiss_fft.h \
		codec2/defines.h \
		codec2/nlp.h \
		codec2/quantise.h \
		codec2/qbase.h \
		iaxcodec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mbedec.o: mbedec.cpp mbedec.h \
		mbelib_parms.h \
		mbelib.h \
		Golay24128.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mbedec.o mbedec.cpp

mbeenc.o: mbeenc.cc mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		Golay24128.h \
		ambe3600x2450_const.h \
		ambe3600x2400_const.h \
		vocoder_tables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mbeenc.o mbeenc.cc

mbelib.o: mbelib.c mbelib.h \
		mbelib_const.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mbelib.o mbelib.c

nxdncodec.o: nxdncodec.cpp nxdncodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nxdncodec.o nxdncodec.cpp

p25codec.o: p25codec.cpp p25codec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o p25codec.o p25codec.cpp

refcodec.o: refcodec.cpp refcodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		CRCenc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o refcodec.o refcodec.cpp

serialambe.o: serialambe.cpp serialambe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialambe.o serialambe.cpp

serialmodem.o: serialmodem.cpp serialmodem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialmodem.o serialmodem.cpp

xrfcodec.o: xrfcodec.cpp xrfcodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		CRCenc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xrfcodec.o xrfcodec.cpp

ysfcodec.o: ysfcodec.cpp ysfcodec.h \
		codec.h \
		audioengine.h \
		serialambe.h \
		serialmodem.h \
		mbedec.h \
		mbeenc.h \
		ambe.h \
		mbelib.h \
		imbe_vocoder/imbe_vocoder.h \
		imbe_vocoder/imbe.h \
		imbe_vocoder/typedef.h \
		imbe_vocoder/typedefs.h \
		imbe_vocoder/dsp_sub.h \
		imbe_vocoder/basic_op.h \
		imbe_vocoder/math_sub.h \
		imbe_vocoder/encode.h \
		imbe_vocoder/decode.h \
		YSFFICH.h \
		YSFConvolution.h \
		CRCenc.h \
		Golay24128.h \
		chamming.h \
		vocoder_tables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ysfcodec.o ysfcodec.cpp

qrc_dudestar.o: qrc_dudestar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_dudestar.o qrc_dudestar.cpp

moc_audioengine.o: moc_audioengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audioengine.o moc_audioengine.cpp

moc_codec.o: moc_codec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codec.o moc_codec.cpp

moc_dcscodec.o: moc_dcscodec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dcscodec.o moc_dcscodec.cpp

moc_dmrcodec.o: moc_dmrcodec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dmrcodec.o moc_dmrcodec.cpp

moc_dudestar.o: moc_dudestar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dudestar.o moc_dudestar.cpp

moc_httpmanager.o: moc_httpmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpmanager.o moc_httpmanager.cpp

moc_iaxcodec.o: moc_iaxcodec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iaxcodec.o moc_iaxcodec.cpp

moc_levelmeter.o: moc_levelmeter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_levelmeter.o moc_levelmeter.cpp

moc_m17codec.o: moc_m17codec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_m17codec.o moc_m17codec.cpp

moc_nxdncodec.o: moc_nxdncodec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nxdncodec.o moc_nxdncodec.cpp

moc_p25codec.o: moc_p25codec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_p25codec.o moc_p25codec.cpp

moc_refcodec.o: moc_refcodec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_refcodec.o moc_refcodec.cpp

moc_serialambe.o: moc_serialambe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialambe.o moc_serialambe.cpp

moc_serialmodem.o: moc_serialmodem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialmodem.o moc_serialmodem.cpp

moc_xrfcodec.o: moc_xrfcodec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xrfcodec.o moc_xrfcodec.cpp

moc_ysfcodec.o: moc_ysfcodec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ysfcodec.o moc_ysfcodec.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/dudestar/bin || mkdir -p $(INSTALL_ROOT)/opt/dudestar/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/dudestar/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/dudestar/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/dudestar/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/dudestar/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

